/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rallye;

import java.awt.Frame;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import rallye.entities.Categoria;
import rallye.entities.Inscripcion;

/**
 *
 * @author usuario
 */
public class PanelDetalle extends javax.swing.JPanel {
    
    private Inscripcion inscripcion;
    private Categoria categoria;
    
    public Categoria getCategoria() {
        return categoria;
    }
    
    /**
     * Creates new form PanelDetalle
     */
    public PanelDetalle() {
        initComponents();  
    }

    public Inscripcion getInscripcion() {
        return inscripcion;
    }

    public void setInscripcion(Inscripcion inscripcion) {
        this.inscripcion = inscripcion;
    }
    
    public void setData(){
        inscripcion.setEscuderia(jTextFieldEscuderia.getText());
        inscripcion.setPiloto(jTextFieldPiloto.getText());
        inscripcion.setVehiculo(jTextFieldVehiculo.getText());
        inscripcion.setCategoria(categoria);
        //Introducir en la base de datos el tiempo.
        Date fecha = null;
        Calendar calendar = null;
        long minutosAmili = Integer.valueOf(jTextFieldMinutos.getText())*60000;
        long segundosAmili = Integer.valueOf(jTextFieldSegundos.getText())*1000;
        long milisegundos= Integer.valueOf(jTextFieldMilisegundos.getText());
        calendar.setTimeInMillis(milisegundos+segundosAmili+minutosAmili);
        inscripcion.setTiempo(calendar.getTime());
        
        inscripcion.setFecha(jDateChooser2.getDate());
        if(jCheckBox1.isSelected()){
            inscripcion.setAutorizado(true);
        }else{
            inscripcion.setAutorizado(false);
        }
    }
    
    public void showData() {
        jTextFieldEscuderia.setText(String.valueOf(inscripcion.getEscuderia()));
        jTextFieldPiloto.setText(String.valueOf(inscripcion.getPiloto()));
        jTextFieldVehiculo.setText(String.valueOf(inscripcion.getVehiculo()));
        jTextFieldCategoria.setText(String.valueOf(inscripcion.getCategoria()));
        
        //Mostrar tipo de dato time.
//        SimpleDateFormat timeFormat = new SimpleDateFormat("dd-MM-yyyy");
//        jTextFieldMinutos.setText(timeFormat.format(inscripcion.getTiempo()));
        
        //Mostrar tipo de dato date(fecha).
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        jDateChooser2.setDate(inscripcion.getFecha());
        
        if(inscripcion.getAutorizado()){
            jCheckBox1.setSelected(true);
        }else{
            jCheckBox1.setSelected(false);
        }
    }
    
    public void showCategoria() {
        if(categoria != null) {
            jTextFieldCategoria.setText(categoria.getNombre());
        }
    }
    
    public void cleanData() {
        jTextFieldEscuderia.setText("");
        jTextFieldPiloto.setText("");
        jTextFieldVehiculo.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldMinutos.setText("");
        jDateChooser2.setCalendar(null);
        jCheckBox1.setSelected(false);
    }
    
    public void editableFalse(){
        jTextFieldEscuderia.setEditable(false);
        jTextFieldPiloto.setEditable(false);
        jTextFieldVehiculo.setEditable(false);
        jTextFieldCategoria.setEditable(false);
        jTextFieldMinutos.setEditable(false);
        jDateChooser2.setEnabled(false);
        jButton1.setEnabled(false);
        jCheckBox1.setEnabled(false);
    }
    
    public void editableTrue(){
        jTextFieldEscuderia.setEditable(true);
        jTextFieldPiloto.setEditable(true);
        jTextFieldVehiculo.setEditable(true);
        jTextFieldCategoria.setEditable(true);
        jTextFieldMinutos.setEditable(true);
        jDateChooser2.setEnabled(true);
        jCheckBox1.setEnabled(true);
        jButton1.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEscuderia = new javax.swing.JTextField();
        jTextFieldPiloto = new javax.swing.JTextField();
        jTextFieldVehiculo = new javax.swing.JTextField();
        jTextFieldMinutos = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSegundos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMilisegundos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(206, 227, 246));

        jTextFieldVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVehiculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Escuderia:");

        jLabel3.setText("Piloto:");

        jLabel4.setText("Vehículo:");

        jLabel5.setText("Tiempo:");

        jLabel6.setText("Fecha:");

        jLabel7.setText("Categoría:");

        jButton1.setText("Seleccionar categoría");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser2.setMinimumSize(new java.awt.Dimension(21, 14));

        jCheckBox1.setText("Autorizado");

        jLabel1.setText("m");

        jLabel8.setText("s");

        jLabel9.setText("ms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jTextFieldPiloto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEscuderia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCategoria))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMilisegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jCheckBox1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldMinutos)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldMilisegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEscuderia)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPiloto)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox1))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCategoria)
                            .addComponent(jButton1))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Tomar una referencia al JFrame que contiene este panel
        Frame frameParent = Frame.getFrames()[0];
        DialogListCategorias dialogListCategorias = new DialogListCategorias(frameParent, true);
        dialogListCategorias.setVisible(true);
         //Obtener el producto que se ha seleccionado en la ventana de diálogo
        categoria = dialogListCategorias.getCategoriaSelec();
        showCategoria();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldEscuderia;
    private javax.swing.JTextField jTextFieldMilisegundos;
    private javax.swing.JTextField jTextFieldMinutos;
    private javax.swing.JTextField jTextFieldPiloto;
    private javax.swing.JTextField jTextFieldSegundos;
    private javax.swing.JTextField jTextFieldVehiculo;
    // End of variables declaration//GEN-END:variables
}
